rootUser: "__MINIO_USER__"
rootPassword: "__MINIO_PASSWORD__"
mode: standalone
replicas: 1
persistence:
  enabled: true
  size: 5Gi
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"
buckets:
  - name: gitlab-artifacts
  - name: gitlab-lfs
  - name: gitlab-uploads
  - name: gitlab-packages
  - name: gitlab-dependency-proxy
  - name: gitlab-pages
  - name: gitlab-mr-diffs
  - name: gitlab-terraform-state
  - name: gitlab-ci-secure-files
  - name: gitlab-backups
  - name: gitlab-tmp