apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-1
data:
  # il simbolo | in yaml fa prendere tutto quello che c e' dopo come valore,
  # cosi' com e', con accapo indentazioni ecc
  index.html: |
    <!DOCTYPE html>
    <html>
      <head><title>App 1</title></head>
      <body>
        <h1>app1</h1>
      </body>
    </html>