# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # configuro la macchina server
  config.vm.define "gpirozziS" do |gpirozziS|
    gpirozziS.vm.hostname = "gpirozziS"
    gpirozziS.vm.network "private_network", ip: "192.168.56.110"
    gpirozziS.vm.provision "shell",
      name: "ssh-config",  
      path: "scripts/ssh-config.sh"
    gpirozziS.vm.provision "shell",
      name: "server-config",  
      env: {"K3S_CLUSTER_TOKEN" => "13ca35076e834959c55701b98d40c104"},
      path: "scripts/server.sh"
    gpirozziS.vm.provider "virtualbox" do |vb|
      vb.name = "gpirozziS"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  config.vm.define "gpirozziSW" do |gpirozziSW|
    gpirozziSW.vm.hostname = "gpirozziSW"
    gpirozziSW.vm.network "private_network", ip: "192.168.56.111"
    gpirozziSW.vm.provision "shell",
      name: "ssh-config",  
      path: "scripts/ssh-config.sh"
    gpirozziSW.vm.provision "shell",
      name: "agent-config",
      env: {"K3S_CLUSTER_TOKEN" => "13ca35076e834959c55701b98d40c104"},
      path: "scripts/agent.sh"
    gpirozziSW.vm.provider "virtualbox" do |vb|
      vb.name = "gpirozziSW"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
end