# -*- mode: ruby -*-
# vi: set ft=ruby :

 env_file = File.join(File.dirname(__FILE__), '.env')
 if File.exist?(env_file)
   File.readlines(env_file).each do |line|
     next if line.strip.empty? || line.start_with?('#')
     
     key, value = line.strip.split('=', 2)
     ENV[key] = value if key && value
   end
 end

K3S_TOKEN = ENV['K3S_CLUSTER_TOKEN'] || "token-sviluppo"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # configuro la macchina server
  config.vm.define "gpirozziS" do |gpirozziS|
    gpirozziS.vm.hostname = "gpirozziS"
    gpirozziS.vm.network "private_network", ip: "192.168.56.110"
    gpirozziS.vm.provision "shell",
      name: "ssh-config",  
      path: "scripts/ssh-config.sh"
    gpirozziS.vm.provision "shell",
      name: "server-config",  
      env: {"K3S_CLUSTER_TOKEN" => K3S_TOKEN},
      path: "scripts/server.sh"
    gpirozziS.vm.provider "virtualbox" do |vb|
      vb.name = "gpirozziS"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # configuro la macchina agent
  config.vm.define "gpirozziSW" do |gpirozziSW|
    gpirozziSW.vm.hostname = "gpirozziSW"
    gpirozziSW.vm.network "private_network", ip: "192.168.56.111"
    gpirozziSW.vm.provision "shell",
      name: "ssh-config",  
      path: "scripts/ssh-config.sh"
    gpirozziSW.vm.provision "shell",
      name: "agent-config",
      env: {"K3S_CLUSTER_TOKEN" => K3S_TOKEN},
      path: "scripts/agent.sh"
    gpirozziSW.vm.provider "virtualbox" do |vb|
      vb.name = "gpirozziSW"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
end